/**
 * config.js — Δημήτριος Μουδιώτης & Συνεργάτες
 * ════════════════════════════════════════════════════════════════════════════
 */

window.SITE_CONFIG = {

    // ── META ──────────────────────────────────────────────────────────────
    meta: {
        titleEl:       'Άδεια Τρέιλερ και Έγκριση Τύπου Οχήματος | Μουδιώτης, Αθήνα',
        titleEn:       'Trailer Licence, Vehicle Type Approval | Moudiotis, Athens',
        descriptionEl: 'Δελτίο κοινοποίησης, καταχώρηση ΤΑΟ και εγκρίσεις τύπου πανελλαδικά. Άδεια τρέιλερ Ο1/Ο2 σε Αθήνα και Θεσσαλονίκη.',
        descriptionEn: 'Type approval notification, TAO registration and vehicle type approval across Greece. O1/O2 trailer licences in Athens and Thessaloniki.',
        lang:          'el',
    },

    // ── PROFILE ───────────────────────────────────────────────────────────
    profile: {
        firstNameEl:   'ΤΕΧΝΙΚΟ ΓΡΑΦΕΙΟ',
        firstNameEn:   'TECHNICAL OFFICE',
        lastNameEl:    'ΔΗΜΗΤΡΙΟΣ\nΜΟΥΔΙΩΤΗΣ',
        lastNameEn:    'DIMITRIOS\nMOUDIOTIS',
        suffixEl:      'ΚΑΙ ΣΥΝΕΡΓΑΤΕΣ',
        suffixEn:      'and Associates',
        initials:      'ΔΜ',
        navBrandEl:    'ΤΕΧΝΙΚΟ ΓΡΑΦΕΙΟ ΜΟΥΔΙΩΤΗΣ',
        navBrandEn:    'MOUDIOTIS TECHNICAL OFFICE',
        displayNameEl: 'Δημήτριος Μουδιώτης και Συνεργάτες',
        displayNameEn: 'Dimitrios Moudiotis and Associates',
        professionEl:  'Μηχανολόγος Μηχανικός ΑΠΘ, MSc',
        professionEn:  'Mechanical Engineer AUTH, MSc',
        fullTitleEl:   'Μηχανολόγος Μηχανικός ΑΠΘ, MSc | Αθήνα - Θεσσαλονίκη',
        fullTitleEn:   'Mechanical Engineer AUTH, MSc | Athens - Thessaloniki',
        universityEl:  '',
        universityEn:  '',
        locationEl:    'Έδρα\u00A0Αθήνα\u00A0-\u00A0Θεσσαλονίκη | Εξυπηρέτηση Πανελλαδικά και\u00A0εντός\u00A0Ε.Ε.',
        locationEn:    'Based\u00A0in\u00A0Athens\u00A0-\u00A0Thessaloniki | Serving all of Greece and\u00A0the\u00A0EU',
        areaEl:        'Αθήνα, Ελλάδα',
        areaEn:        'Athens, Greece',
        expStartYear:  2016,
    },

    // ── ASSETS ────────────────────────────────────────────────────────────
    assets: {
        logo:         '/logo.webp',
        photo:        '/founder.webp',
        contactPhoto: '/founder_contact.webp',
        heroSlides:   [],
    },

    // ── CONTACT ───────────────────────────────────────────────────────────
    contact: {
        phone:     '210 756 1836',
        phoneEn:   '0030 210 756 1836',
        phoneTel:  'tel:+302107561836',
        fax:       '',
        email:     'moudiotis.meng@gmail.com',
        address:   'Έδρα Αθήνα - Θεσσαλονίκη | Εξυπηρέτηση Πανελλαδικά και εντός Ε.Ε.',
        addressEn: 'Based in Athens - Thessaloniki | Serving all of Greece and the EU',
        facebook:  'https://www.facebook.com/61550061850076',
        linkedin:  'https://www.linkedin.com/in/moudiotis/',
        mapsUrl:   'https://maps.google.com/maps?q=37.9649217,23.7459572&hl=el&z=17&output=embed',
    },

    // ── THEME ─────────────────────────────────────────────────────────────
    theme: {
        accent:      '#1d3a5c',
        accentLight: '#2e5f8a',
    },

    // ── MARQUEE ───────────────────────────────────────────────────────────
    marquee: [
        { el: 'Ταξινόμηση Οχήματος',               en: 'Vehicle Registration' },
        { el: 'Έγκριση Τύπου Οχήματος',            en: 'Vehicle Type Approval' },
        { el: 'Άδεια Τρέιλερ Ο1 / Ο2',            en: 'O1 / O2 Trailer Licence' },
        { el: 'Έγκριση Τύπου Ρυμουλκούμενου',      en: 'Trailer Type Approval' },
        { el: 'Άδεια Μπαγκαζιέρας',                en: 'Cargo Trailer Licence' },
        { el: 'Οχήματα Ειδικής Χρήσης',            en: 'Special Use Vehicles' },
        { el: 'Μελέτες Οχημάτων',                  en: 'Vehicle Studies' },
        { el: 'Εγκρίσεις Τύπου',                   en: 'Type Approvals' },
        { el: 'Μεμονωμένη Έγκριση Οχήματος',       en: 'Individual Vehicle Approval' },
        { el: 'Καταχώρηση στο ΤΑΟ',                en: 'Technical Vehicle Archive (TAO)' },
        { el: 'Δελτίο Κοινοποίησης',               en: 'Notification Certificate' },
        { el: 'Ειδικές Κατασκευές και Μετασκευές',   en: 'Special Bodywork and Conversions' },
        { el: 'Ταξινόμηση Τροχόσπιτου',             en: 'Caravan Registration' },
        { el: 'Τοποθέτηση Γερανού σε Όχημα',      en: 'Vehicle Crane Installation' },
        { el: 'Βαν σε Αυτοκινούμενο Τροχόσπιτο',    en: 'Van to Motor Caravan' },
        // Κρυφά (όχι οχήματα) — για μελλοντική χρήση:
        // { el: 'Τεχνικός Ασφαλείας — ΓΕΕΚ',         en: 'Safety Engineer — Risk Assessment' },
        // { el: '3D Printing and CAD',                  en: '3D Printing and CAD' },
        // { el: 'Laser Cut και Κατεργασία Μετάλλου',   en: 'Laser Cut and Sheet Metal' },
    ],

    // ── ABOUT ─────────────────────────────────────────────────────────────
    about: {
        headingEl: 'Εμπειρία &amp; <em>Εξειδίκευση</em>',
        headingEn: 'Experience &amp; <em>Expertise</em>',
        leadEl:    'Με {years}+ χρόνια εμπειρίας, το <strong class="kw">τεχνικό γραφείο</strong> του <strong class="kw">μηχανολόγου μηχανικού</strong> Δημήτρη Μουδιώτη αναλαμβάνει <strong class="kw">έγκριση τύπου οχήματος</strong> και <strong class="kw">έγκριση τύπου ρυμουλκούμενου</strong>, <strong class="kw">άδεια τρέιλερ</strong> Ο1/Ο2, <strong class="kw">άδεια μπαγκαζιέρας</strong>, μελέτες <strong class="kw">οχημάτων ειδικής χρήσης ειδικού σκοπού</strong>, μετασκευές, τροχόσπιτα και τοποθέτηση γερανών.',
        leadEn:    'With {years}+ years of experience, the <strong class="kw">technical office</strong> of <strong class="kw">mechanical engineer</strong> Dimitrios Moudiotis handles <strong class="kw">vehicle type approval</strong> and <strong class="kw">trailer type approval</strong>, <strong class="kw">trailer and cargo-box licences</strong> O1/O2, <strong class="kw">special use / special purpose vehicle</strong> studies, conversions, caravans and crane installations.',
        features: [
            {
                icon:    'fa-bolt-lightning',
                labelEl: 'Άμεση Εξυπηρέτηση',
                labelEn: 'Fast Service',
                textEl:  'Γρήγορη ανταπόκριση και <strong class="kw">έκδοση αδειών</strong> χωρίς καθυστερήσεις',
                textEn:  'Rapid response and <strong class="kw">permit issuance</strong> without delays',
            },
            {
                icon:    'fa-crosshairs',
                labelEl: 'Ακρίβεια',
                labelEn: 'Precision',
                textEl:  'Κάθε μελέτη εκπονείται με <strong class="kw">μεθοδολογική ακρίβεια</strong> και πλήρη τεκμηρίωση',
                textEn:  'Every study prepared with <strong class="kw">methodological precision</strong> and full documentation',
            },
            {
                icon:    'fa-list-check',
                labelEl: 'Πλήρης Ανάληψη Διαδικασίας',
                labelEn: 'End-to-End Process',
                textEl:  'Αναλαμβάνουμε <strong class="kw">ολόκληρη τη διαδικασία</strong> — από τα δικαιολογητικά ώς την έκδοση άδειας',
                textEn:  'We handle the <strong class="kw">entire process</strong> — from documents to licence issuance',
            },
        ],
    },

    // ── SERVICES ──────────────────────────────────────────────────────────
    services: [
        {
            featured:    true,
            icon:        'fa-file-circle-check',
            urlEl:       '/deltio-koinopoiisis-tao/',
            urlEn:       '/en/deltio-koinopoiisis-tao/',
            titleEl:     'Δελτίο Κοινοποίησης και Καταχώρηση ΤΑΟ',
            titleEn:     'Notification Certificate and TAO Registration',
            textEl:      '<strong class="kw">Δελτίο Κοινοποίησης</strong> έγκρισης τύπου και <strong class="kw">καταχώρηση στο ΤΑΟ</strong> για εισαγωγείς, αντιπροσωπείες και κατασκευαστές, σε όλη την Ελλάδα και για το εξωτερικό.',
            textEn:      '<strong class="kw">Type approval notification</strong> and <strong class="kw">TAO registration</strong> for importers, dealers and manufacturers, across Greece and for clients abroad.',
            seoKeywords: 'δελτίο κοινοποίησης, καταχώρηση ΤΑΟ, Τεχνικό Αρχείο Οχημάτων, ταξινόμηση οχήματος, εισαγωγή οχημάτων, type approval notification Greece, TAO registration',
        },
        {
            icon:        'fa-stamp',
            urlEl:       '/ethniki-evropaiki-egkrisi-typou/',
            urlEn:       '/en/ethniki-evropaiki-egkrisi-typou/',
            titleEl:     'Εθνική και Ευρωπαϊκή Έγκριση Τύπου',
            titleEn:     'National and EU Type Approval',
            textEl:      'Φάκελος <strong class="kw">έγκρισης τύπου</strong> για οχήματα, αμαξώματα και ρυμουλκούμενα, κατά τον Κανονισμό (ΕΕ) 2018/858 ή σε εθνικό επίπεδο για μικρές σειρές.',
            textEn:      '<strong class="kw">Type approval</strong> dossiers for vehicles, bodies and trailers, under Regulation (EU) 2018/858 or at national level for small series.',
            seoKeywords: 'έγκριση τύπου οχήματος, ευρωπαϊκή έγκριση τύπου, εθνική έγκριση τύπου, μικρή σειρά, κανονισμός 2018/858, vehicle type approval Greece',
        },
        {
            icon:        'fa-car-side',
            urlEl:       '/memonomeni-egkrisi-oximatos/',
            urlEn:       '/en/memonomeni-egkrisi-oximatos/',
            titleEl:     'Μεμονωμένη Έγκριση και Εισαγόμενα Οχήματα',
            titleEn:     'Individual Approval and Imported Vehicles',
            textEl:      'Για οχήματα που δεν καλύπτονται από έγκριση τύπου: <strong class="kw">εισαγόμενα</strong>, τροποποιημένα ή μοναδικά, μέχρι την ταξινόμηση.',
            textEn:      'For vehicles not covered by a type approval: <strong class="kw">imported</strong>, modified or one-off, through to registration.',
            seoKeywords: 'μεμονωμένη έγκριση οχήματος, εισαγόμενο όχημα ταξινόμηση, όχημα από ΗΠΑ, individual vehicle approval Greece',
        },
        {
            icon:        'fa-motorcycle',
            urlEl:       '/egkrisi-typou-dikyklon/',
            urlEn:       '/en/egkrisi-typou-dikyklon/',
            titleEl:     'Έγκριση Τύπου Κατηγορίας L',
            titleEn:     'Category L Type Approval',
            textEl:      '<strong class="kw">Μοτοποδήλατα</strong>, μοτοσικλέτες, τρίκυκλα και τετράκυκλα κατά τον Κανονισμό (ΕΕ) 168/2013.',
            textEn:      '<strong class="kw">Mopeds</strong>, motorcycles, tricycles and quadricycles under Regulation (EU) 168/2013.',
            seoKeywords: 'έγκριση τύπου μοτοσικλέτας, κατηγορία L, τετράκυκλο ταξινόμηση, 168/2013, L category type approval Greece',
        },
        {
            badge:       'new',
            expand:      '0',
            icon:        'fa-truck-ramp-box',
            urlEl: '/adeia-treiler-o1-o2/',
            urlEn: '/en/adeia-treiler-o1-o2/',
            titleEl:     'Άδεια Τρέιλερ Ο1 και Ο2 — Ταξινόμηση Ρυμουλκούμενου και Μπαγκαζιέρας',
            titleEn:     'O1 and O2 Trailer Licence — Trailer and Cargo Box Registration',
            textEl:      'Ξανάνοιξαν οι διαδικασίες <strong class="kw">ταξινόμησης</strong> για <strong class="kw">όλα τα τρέιλερ</strong>. Αναλαμβάνουμε πλήρως: <strong class="kw">Ο1</strong> (έως 750 kg — <strong class="kw">μπαγκαζιέρα</strong>, σκάφος, τροχόσπιτο) και <strong class="kw">Ο2</strong> (έως 3,5 τόνους). <strong class="kw">Έγκριση τύπου ρυμουλκούμενου</strong>, τεχνική μελέτη, υποβολή σε ΥΜΕΔ/ΚΤΕΟ, <strong class="kw">έκδοση άδειας κυκλοφορίας</strong> — από την αρχή ώς το τέλος.',
            textEn:      'Procedures have reopened for <strong class="kw">all trailers</strong>. We handle everything: <strong class="kw">O1</strong> (up to 750 kg — cargo box, boat, caravan) and <strong class="kw">O2</strong> (up to 3.5 tonnes). <strong class="kw">Trailer type approval</strong>, technical study, submission to YMED/KTEO, <strong class="kw">circulation licence issuance</strong> — end to end.',
            seoKeywords: 'αδεια τρειλερ, άδεια τρέιλερ, τρέϊλερ, ταξινόμηση ρυμουλκούμενου, έγκριση τύπου ρυμουλκούμενου, αδεια ρυμουλκουμενου Ο1 Ο2, άδεια ρυμουλκούμενου, μπαγκαζιέρα, άδεια μπαγκαζιέρα, νομιμοποίηση τρέιλερ, ταξινόμηση τρέιλερ, έκδοση άδειας κυκλοφορίας, trailer licence Greece, cargo trailer licence Greece',
        },
        {
            icon:        'fa-caravan',
            urlEl:       '/trochospita/',
            urlEn:       '/en/trochospita/',
            titleEl:     'Ταξινόμηση Τροχόσπιτου',
            titleEn:     'Caravan Registration',
            textEl:      'Ρυμουλκούμενο <strong class="kw">τροχόσπιτο</strong>, καινούργιο ή εισαγόμενο μεταχειρισμένο: ταξινόμηση, άδεια κυκλοφορίας και πινακίδες.',
            textEn:      'Trailer <strong class="kw">caravan</strong>, new or imported used: registration, licence and plates.',
            seoKeywords: 'ταξινόμηση τροχόσπιτου, άδεια τροχόσπιτου, τροχόσπιτο από Γερμανία, caravan registration Greece',
        },
        {
            icon:        'fa-van-shuttle',
            urlEl:       '/metatropi-van-se-trochospito/',
            urlEn:       '/en/metatropi-van-se-trochospito/',
            titleEl:     'Μετατροπή Βαν σε Αυτοκινούμενο Τροχόσπιτο',
            titleEn:     'Van to Motor Caravan Conversion',
            textEl:      'Η μετατροπή γίνεται <strong class="kw">υπό προϋποθέσεις</strong> και ολοκληρώνεται με έλεγχο και νέα άδεια κυκλοφορίας. Εξετάζουμε πρώτα το δικό σας όχημα.',
            textEn:      'The conversion is possible <strong class="kw">under conditions</strong> and ends with an inspection and a new registration. We assess your vehicle first.',
            seoKeywords: 'μετατροπή βαν σε τροχόσπιτο, αυτοκινούμενο τροχόσπιτο, camper άδεια, van to camper Greece',
        },
        {
            icon:        'fa-truck-medical',
            urlEl:       '/oximata-eidikou-skopou/',
            urlEn:       '/en/oximata-eidikou-skopou/',
            titleEl:     'Οχήματα Ειδικής Χρήσης και Ειδικού Σκοπού',
            titleEn:     'Special Use and Special Purpose Vehicles',
            textEl:      '<strong class="kw">Καντίνες</strong>, ασθενοφόρα, κινητές μονάδες, οχήματα οδικής βοήθειας: ταξινόμηση και έγκριση από τη σωστή διαδρομή.',
            textEn:      '<strong class="kw">Catering units</strong>, ambulances, mobile units, recovery vehicles: registration and approval by the right route.',
            seoKeywords: 'οχήματα ειδικής χρήσης ειδικού σκοπού, ΕΧΕΣ, καντίνα άδεια, ασθενοφόρο ταξινόμηση, special purpose vehicle registration Greece',
        },
        {
            icon:        'fa-compass-drafting',
            urlEl:       '/metaskeves-yperkataskeves/',
            urlEn:       '/en/metaskeves-yperkataskeves/',
            titleEl:     'Μετασκευές και Υπερκατασκευές',
            titleEn:     'Conversions and Superstructures',
            textEl:      'Αλλαγή αμαξώματος, κινητήρα ή αξόνων, ψυγεία, ανατροπές, κινητά συνεργεία. <strong class="kw">Μελέτη αντοχής</strong> και νέα άδεια κυκλοφορίας.',
            textEn:      'Body, engine or axle changes, refrigerated bodies, tippers, mobile workshops. <strong class="kw">Strength study</strong> and new registration.',
            seoKeywords: 'μετασκευή οχήματος, αλλαγή αμαξώματος, αλλαγή κινητήρα, προσθήκη άξονα, υπερκατασκευή, vehicle conversion Greece',
        },
        {
            icon:        'fa-truck-moving',
            urlEl:       '/topothetisi-geranou/',
            urlEn:       '/en/topothetisi-geranou/',
            titleEl:     'Τοποθέτηση Γερανού σε Όχημα',
            titleEn:     'Crane Installation on a Vehicle',
            textEl:      'Μελέτη φορτίων και ευστάθειας, στερέωση στο πλαίσιο, έλεγχος και <strong class="kw">νέα άδεια κυκλοφορίας</strong>.',
            textEn:      'Load and stability study, chassis mounting, inspection and a <strong class="kw">new registration certificate</strong>.',
            seoKeywords: 'τοποθέτηση γερανού σε όχημα, γερανοφόρο άδεια, μελέτη τοποθέτησης γερανού, vehicle crane installation Greece',
        },
        // ── Κρυφές (δεν εμφανίζονται· κρατιούνται για μελλοντική χρήση) ──
        {
            hidden:      true,   // κρυφή (όχι οχήματα)
            featured:    true,
            icon:        'fa-file-circle-check',
            urlEl: '/deltio-koinopoiisis-tao/',
            urlEn: '/en/deltio-koinopoiisis-tao/',
            titleEl:     'Δελτίο Κοινοποίησης, Καταχώρηση ΤΑΟ και Εγκρίσεις Τύπου',
            titleEn:     'Type Approval Notification, TAO Registration and Type Approvals',
            textEl:      '<strong class="kw">Δελτίο Κοινοποίησης</strong> έγκρισης τύπου και <strong class="kw">καταχώρηση στο ΤΑΟ</strong> για εισαγωγείς, αντιπροσωπείες και κατασκευαστές, σε όλη την Ελλάδα και για το εξωτερικό. Εθνική και ευρωπαϊκή <strong class="kw">έγκριση τύπου</strong>, <strong class="kw">μεμονωμένη έγκριση</strong>, κατηγορία L. Φάκελος που δεν συγχωρεί λάθη — τον αναλαμβάνουμε ολόκληρο.',
            textEn:      '<strong class="kw">Type approval notification</strong> and <strong class="kw">TAO registration</strong> for importers, dealers and manufacturers, across Greece and for clients abroad. National and European <strong class="kw">type approval</strong>, <strong class="kw">individual approval</strong>, category L. A dossier that forgives no mistakes — we take it on in full.',
            seoKeywords: 'έγκριση τύπου οχήματος, έγκριση τύπου ρυμουλκούμενου, εθνική έγκριση τύπου, ευρωπαϊκή έγκριση τύπου, μεμονωμένη έγκριση οχήματος, καταχώρηση ΤΑΟ, Τεχνικό Αρχείο Οχημάτων, δελτίο κοινοποίησης, ταξινόμηση οχήματος, ταξινομιση αδεας οχηματος, οχήματα ειδικής χρήσης ειδικού σκοπού, εγκριση τυπου, μελετη οχηματος, vehicle type approval Greece, trailer type approval, individual vehicle approval Greece, special purpose vehicle registration Greece',
            items: [
                {
                    titleEl: 'Εθνική και Ευρωπαϊκή Έγκριση Τύπου',
                    titleEn: 'National and European Type Approval',
                    textEl:  'Πλήρης σύνταξη και διαχείριση φακέλου για την έκδοση εθνικών ή ευρωπαϊκών εγκρίσεων τύπου οχημάτων, ρυμουλκούμενων και εξαρτημάτων.',
                    textEn:  'Complete preparation and management of the dossier for issuing national or European type approvals for vehicles, trailers and components.',
                },
                {
                    urlEl: '/memonomeni-egkrisi-oximatos/',
                    urlEn: '/en/memonomeni-egkrisi-oximatos/',
                    titleEl: 'Μεμονωμένη Έγκριση Οχημάτων',
                    titleEn: 'Individual Vehicle Approval',
                    textEl:  'Μεμονωμένα, ειδικά, τροποποιημένα ή εισαγόμενα οχήματα πιστοποιούνται ώστε να εκδοθεί άδεια κυκλοφορίας.',
                    textEn:  'Individual, special, modified or imported vehicles are certified so that a registration certificate can be issued.',
                },
                {
                    urlEl: '/egkrisi-typou-dikyklon/',
                    urlEn: '/en/egkrisi-typou-dikyklon/',
                    titleEl: 'Έγκριση Τύπου Κατηγορίας L',
                    titleEn: 'Category L Type Approval',
                    textEl:  'Μοτοποδήλατα, μοτοσικλέτες, τρίκυκλα και τετράκυκλα κατά τον Καν. (ΕΕ) 168/2013 — κατάταξη, τεχνικό αρχείο και καταχώρηση.',
                    textEn:  'Mopeds, motorcycles, tricycles and quadricycles under Reg. (EU) 168/2013 — classification, technical file and registration.',
                },
                {
                    urlEl: '/deltio-koinopoiisis-tao/',
                    urlEn: '/en/deltio-koinopoiisis-tao/',
                    titleEl: 'Καταχώρηση στο ΤΑΟ',
                    titleEn: 'Technical Vehicle Archive (TAO) Registration',
                    textEl:  'Καταχώρηση στο Τεχνικό Αρχείο Οχημάτων του Υπουργείου Υποδομών και Μεταφορών. Τη διαδικασία τη διεκπεραιώνουμε εμείς.',
                    textEn:  'Registration in the Technical Vehicle Archive of the Ministry of Infrastructure and Transport. We handle the procedure.',
                },
                {
                    urlEl: '/deltio-koinopoiisis-tao/',
                    urlEn: '/en/deltio-koinopoiisis-tao/',
                    titleEl: 'Δελτία Κοινοποίησης',
                    titleEn: 'Notification Certificates',
                    textEl:  'Σύνταξη, υποβολή και έκδοση Δελτίου Κοινοποίησης Έγκρισης Τύπου για την ταξινόμηση οχημάτων.',
                    textEn:  'Preparation, submission and issue of the Type Approval Notification Certificate for vehicle registration.',
                },
            ],
        },
        {
            hidden:      true,   // κρυφή (όχι οχήματα)
            expand:      '1',
            urlEl:       '/oximata-eidikou-skopou/',
            urlEn:       '/en/oximata-eidikou-skopou/',
            icon:        'fa-compass-drafting',
            titleEl:     'Τεχνικές Μελέτες και Ειδικές Κατασκευές',
            titleEn:     'Technical Studies and Special Bodywork',
            textEl:      'Σχεδιασμός <strong class="kw">από την αρχή</strong>, υπολογισμοί αντοχής και πιστοποίηση <strong class="kw">ειδικών υπερκατασκευών</strong> και <strong class="kw">μετασκευών</strong> — ψυγεία, γερανοί, ανατροπές, κινητά συνεργεία, ειδικά ρυμουλκούμενα. Μελέτες <strong class="kw">τροποποίησης και συμμόρφωσης</strong> για κάθε αλλαγή στο όχημα.',
            textEn:      'Design <strong class="kw">from scratch</strong>, strength calculations and certification of <strong class="kw">special superstructures</strong> and <strong class="kw">conversions</strong> — refrigerated bodies, cranes, tippers, mobile workshops, special trailers. <strong class="kw">Modification and compliance studies</strong> for every change to the vehicle.',
            seoKeywords: 'τεχνική μελέτη οχήματος, μελέτη αμαξώματος, υπολογισμοί αντοχής, έγκριση ειδικών κατασκευών, μετασκευή οχήματος, υπερκατασκευή, ψυγείο φορτηγού, γερανός οχήματος, ανατροπή, κινητό συνεργείο, ειδικά ρυμουλκούμενα, αλλαγή αμαξώματος, αλλαγή κινητήρα, προσθήκη άξονα, αφαίρεση άξονα, μελέτη τροποποίησης οχήματος, vehicle body study Greece, vehicle conversion approval Greece',
            items: [
                {
                    titleEl: 'Τεχνικές Μελέτες από την Αρχή',
                    titleEn: 'Technical Studies from Scratch',
                    textEl:  'Ολοκληρωμένος σχεδιασμός, υπολογισμοί αντοχής και σύνταξη τεχνικών υπομνημάτων για νέα οχήματα, αμαξώματα ή ρυμουλκούμενα.',
                    textEn:  'Complete design, strength calculations and preparation of technical memoranda for new vehicles, bodies or trailers.',
                },
                {
                    titleEl: 'Έγκριση Ειδικών Κατασκευών και Μετασκευών',
                    titleEn: 'Approval of Special Bodywork and Conversions',
                    textEl:  'Ψυγεία, γερανοί, ανατροπές, κινητά συνεργεία, ειδικά ρυμουλκούμενα — πιστοποίηση ειδικών υπερκατασκευών.',
                    textEn:  'Refrigerated bodies, cranes, tippers, mobile workshops, special trailers — certification of special superstructures.',
                },
                {
                    titleEl: 'Μελέτες Τροποποίησης και Συμμόρφωσης',
                    titleEn: 'Modification and Compliance Studies',
                    textEl:  'Τεχνικές μελέτες για αλλαγή αμαξώματος, αλλαγή κινητήρα, προσθήκη ή αφαίρεση αξόνων και μετατροπές ειδικής χρήσης.',
                    textEn:  'Technical studies for body replacement, engine replacement, addition or removal of axles and special-use conversions.',
                },
            ],
        },
        {
            hidden:      true,   // κρυφή (όχι οχήματα)
            urlEl:       '/ydravliki-platforma/',
            urlEn:       '/en/ydravliki-platforma/',
            icon:        'fa-arrows-up-down',
            titleEl:     'Μελέτη Τοποθέτησης Υδραυλικής Πλατφόρμας — Έγκριση Τύπου',
            titleEn:     'Hydraulic Platform Installation Study — Type Approval',
            textEl:      'Τεχνική μελέτη για την εγκατάσταση <strong class="kw">υδραυλικών πλατφορμών</strong> σε οχήματα και σε σταθερές εγκαταστάσεις. Συμμόρφωση με το <strong class="kw">ΕΝ 1570</strong>, <strong class="kw">σήμανση CE</strong> και <strong class="kw">έγκριση τύπου</strong>. Αθήνα και Θεσσαλονίκη.',
            textEn:      'Technical study by a <strong class="kw">mechanical engineer</strong> for <strong class="kw">hydraulic platform</strong> installation on vehicles and fixed installations. Compliance with <strong class="kw">EN 1570</strong>, <strong class="kw">CE certification</strong> and <strong class="kw">type approval</strong> — Athens and Thessaloniki.',
            seoKeywords: 'υδραυλικη πλατφορμα, εγκριση τυπου, EN 1570, πιστοποιηση CE, hydraulic platform study Greece, τεχνική μελέτη υδραυλικής πλατφόρμας',
        },
        {
            desktopOnly: true,   // κάρτα μόνο στον υπολογιστή (>768px): κλείνει συμμετρικά το πλέγμα· η σελίδα της υπάρχει για όλους
            urlEl:       '/texniki-symvouleftiki/',
            urlEn:       '/en/texniki-symvouleftiki/',
            icon:        'fa-clipboard-check',
            titleEl:     'Τεχνική Συμβουλευτική και Πιστοποίηση',
            titleEn:     'Technical Consulting and Certification',
            textEl:      '<strong class="kw">Εκπροσώπηση</strong> και τεχνική υποστήριξη έναντι ελεγκτικών οργανισμών, τεχνικών υπηρεσιών και εργαστηρίων δοκιμών. Έκδοση επίσημων <strong class="kw">βεβαιώσεων μηχανικού</strong> για τελωνεία, ΚΤΕΟ, Διευθύνσεις Μεταφορών και φακέλους ταξινόμησης.',
            textEn:      '<strong class="kw">Representation</strong> and technical support before inspection bodies, technical services and testing laboratories. Issuing official <strong class="kw">engineer certificates</strong> for customs, KTEO, Transport Directorates and registration dossiers.',
            seoKeywords: 'διαχείριση φακέλων πιστοποίησης, τεχνική συμβουλευτική οχημάτων, βεβαίωση μηχανικού, βεβαίωση συμμόρφωσης, τεχνικό υπόμνημα, τελωνείο όχημα, ΚΤΕΟ βεβαίωση, Διεύθυνση Μεταφορών, εργαστήριο δοκιμών, ελεγκτικός οργανισμός, vehicle certification consulting Greece, engineer compliance certificate Greece',
            items: [
                {
                    titleEl: 'Διαχείριση Φακέλων Πιστοποίησης',
                    titleEn: 'Certification Dossier Management',
                    textEl:  'Απέναντι σε ελεγκτικούς οργανισμούς, τεχνικές υπηρεσίες και εργαστήρια δοκιμών, το γραφείο σάς εκπροσωπεί και σας υποστηρίζει τεχνικά.',
                    textEn:  'Before inspection bodies, technical services and testing laboratories, the office represents you and provides technical support.',
                },
                {
                    titleEl: 'Βεβαιώσεις Συμμόρφωσης και Τεχνικά Υπομνήματα',
                    titleEn: 'Compliance Certificates and Technical Memoranda',
                    textEl:  'Έκδοση επίσημων βεβαιώσεων μηχανικού για τελωνεία, ΚΤΕΟ, Διευθύνσεις Μεταφορών και φακέλους ταξινόμησης.',
                    textEn:  'Issuing official engineer certificates for customs, KTEO, Transport Directorates and registration dossiers.',
                },
            ],
        },
        {
            hidden:      true,   // κρυφή (όχι οχήματα)
            urlEl:       '/meleti-pyroprostasias/',
            urlEn:       '/en/meleti-pyroprostasias/',
            icon:        'fa-fire-extinguisher',
            titleEl:     'Μελέτη Ενεργητικής Πυροπροστασίας',
            titleEn:     'Active Fire Protection Study — Mechanical Engineer',
            textEl:      'Εκπόνηση <strong class="kw">μελέτης ενεργητικής πυροπροστασίας</strong> για κτίρια, βιομηχανικούς και εμπορικούς χώρους. Σχεδιασμός <strong class="kw">συστημάτων κατάσβεσης</strong> (sprinkler, αφρού, CO₂), υπολογισμοί παροχής και υδραυλικές μελέτες — κατά <strong class="kw">ΕΝ 12845</strong> και την ελληνική νομοθεσία. Αθήνα και Θεσσαλονίκη.',
            textEn:      '<strong class="kw">Active fire protection study</strong> by a <strong class="kw">mechanical engineer</strong> for buildings, industrial facilities and commercial premises. Design of <strong class="kw">fire suppression systems</strong> (sprinklers, foam, CO₂), flow calculations, hydraulic studies — compliant with <strong class="kw">EN 12845</strong> and Greek legislation. Athens and Thessaloniki.',
            seoKeywords: 'μελετη ενεργητικης πυροπροστασιας, ενεργητική πυροπροστασία, μελέτη πυροπροστασίας, συστημα πυροσβεσης, sprinkler, πυρασφάλεια κτιρίου, fire protection study Greece, μηχανολόγος μηχανικός πυροπροστασία',
        },
        {
            hidden:      true,   // κρυφή (όχι οχήματα)
            urlEl:       '/texnikos-asfaleias/',
            urlEn:       '/en/texnikos-asfaleias/',
            icon:        'fa-helmet-safety',
            titleEl:     'Τεχνικός Ασφαλείας — Υγεία και Ασφάλεια Εργασίας (Ν.3850/2010)',
            titleEn:     'Safety Engineer — Occupational Health and Safety (Law 3850/2010)',
            textEl:      'Η κάλυψη <strong class="kw">Τεχνικού Ασφαλείας</strong> για <strong class="kw">κάθε επιχείρηση</strong>, ακόμα και με 1 εργαζόμενο είναι υποχρεωτική. Σύνταξη <strong class="kw">ΓΕΕΚ</strong>, εκπαιδεύσεις εργαζομένων, σχέδια εκκένωσης, προετοιμασία ΣΕΠΕ.',
            textEn:      'Mandatory <strong class="kw">Safety Engineer</strong> coverage by a <strong class="kw">mechanical engineer</strong> for <strong class="kw">every business</strong>, even with 1 employee — Athens and Thessaloniki. Written risk assessment (<strong class="kw">GEEK</strong>), employee training, evacuation plans, SEPE preparation.',
            seoKeywords: 'τεχνικος ασφαλειας, ΓΕΕΚ, υγεια ασφαλεια εργασιας, νομος 3850 2010, safety engineer Athens, occupational health safety Greece',
        },
        {
            hidden:      true,   // κρυφή (όχι οχήματα)
            icon:        'fa-cube',
            url:         'https://expertease.eu/3dprint',
            titleEl:     '<strong>Μηχανολογικός Σχεδιασμός</strong> και 3D Printing',
            titleEn:     '<strong>Mechanical Design</strong> and 3D Printing',
            textEl:      '<strong class="kw">Μηχανολόγος μηχανικός</strong> για CAD 3D, FEA ανάλυση αντοχών, <strong class="kw">rapid prototyping</strong>. FDM, SLA, SLS τεχνολογίες εκτύπωσης για ακριβή εξαρτήματα και πρωτότυπα. Laser cut και κατεργασία φύλλων μετάλλου — Αθήνα και Θεσσαλονίκη.',
            textEn:      '<strong class="kw">Mechanical engineer</strong> for CAD 3D, FEA strength analysis, <strong class="kw">rapid prototyping</strong>. FDM, SLA, SLS printing for precision parts and prototypes. Laser cutting and sheet metal work — Athens and Thessaloniki.',
            seoKeywords: 'μηχανολογικος σχεδιασμος, 3D printing Αθηνα, CAD μηχανολογος, rapid prototyping, FEA αναλυση, mechanical design Athens',
        },
    ],

    // ── TRUST ─────────────────────────────────────────────────────────────
    trust: {
        eyebrowEl: 'Γιατί να μας εμπιστευτείτε',
        eyebrowEn: 'Why trust us',
        headingEl: 'Εμπειρία που <em>μιλάει</em>',
        headingEn: 'Experience that <em>speaks</em>',
        stats: [
            { numEl: '{years}+', numEn: '{years}+', labelEl: 'Χρόνια Εμπειρίας',    labelEn: 'Years of Experience' },
            { numEl: '300+',    numEn: '300+',    labelEl: 'Ολοκληρωμένα Έργα',    labelEn: 'Completed Projects' },
            { numEl: '100%',    numEn: '100%',    labelEl: 'Επιτυχείς Εγκρίσεις',  labelEn: 'Successful Approvals' },
        ],
        pillars: [
            {
                icon:    'fa-gear',
                titleEl: 'Τεχνική Επάρκεια',
                titleEn: 'Technical Competence',
                textEl:  'Εξειδικευμένες γνώσεις σε κάθε τύπο οχήματος και μηχανήματος — από απλές βεβαιώσεις έως σύνθετες μελέτες ειδικού εξοπλισμού.',
                textEn:  'Specialised knowledge across all vehicle and machinery types — from simple certificates to complex special equipment studies.',
            },
            {
                icon:    'fa-scale-balanced',
                titleEl: 'Νομική Ασφάλεια',
                titleEn: 'Legal Security',
                textEl:  'Πλήρης συμμόρφωση με την ισχύουσα νομοθεσία. Κάθε μελέτη και έγκριση εκδίδεται με ακρίβεια και νομική κάλυψη.',
                textEn:  'Full compliance with current legislation. Every study and approval is issued with precision and legal coverage.',
            },
            {
                icon:    'fa-handshake',
                titleEl: 'Αξιοπιστία και Συνέπεια',
                titleEn: 'Reliability and Consistency',
                textEl:  'Τηρούμε προθεσμίες, ενημερώνουμε συνεχώς και παρακολουθούμε κάθε υπόθεση από την αρχή έως την έκδοση της τελικής άδειας.',
                textEn:  'We meet deadlines, keep you informed, and follow every case from start to final permit issuance.',
            },
        ],
    },

    // ── ARTICLES TICKER ───────────────────────────────────────────────────
    articles: [
        {
            url:     'https://www.fhwa.dot.gov/reports/tswstudy/vehiclsaf.htm',
            catEl:   'Μελέτες Οχημάτων',
            catEn:   'Vehicle Studies',
            titleEl: 'Τι περιλαμβάνει μια τεχνική μελέτη οχήματος',
            titleEn: 'What a vehicle technical study includes',
            textEl:  'Η τεχνική μελέτη οχήματος αφορά την αξιολόγηση κατασκευαστικών χαρακτηριστικών, αξόνων φόρτωσης και συστημάτων ασφαλείας σύμφωνα με τις ευρωπαϊκές οδηγίες.',
            textEn:  'A vehicle technical study covers the evaluation of structural characteristics, load axles and safety systems in accordance with European directives.',
        },
        {
            url:     'https://eur-lex.europa.eu/EN/legal-content/summary/eu-approval-and-market-surveillance-measures-for-motor-vehicles-and-their-trailers.html',
            catEl:   'Εγκρίσεις Τύπου',
            catEn:   'Type Approvals',
            titleEl: 'Έγκριση τύπου ΕΕ: τι ορίζει ο Κανονισμός 2018/858',
            titleEn: 'EU Type Approval: what Regulation 2018/858 covers',
            textEl:  'Ο Κανονισμός (ΕΕ) 2018/858 ορίζει τη διαδικασία έγκρισης τύπου για μηχανοκίνητα οχήματα και ρυμουλκούμενα. Από την κατάθεση φακέλου έως την τελική χορήγηση.',
            textEn:  'Regulation (EU) 2018/858 sets out the type approval process for motor vehicles and trailers. From file submission to final granting.',
        },
        {
            url:     'https://www.escargo.it/en/category-o-vehicles-what-are-they',
            catEl:   'Ρυμουλκούμενα',
            catEn:   'Trailers',
            titleEl: 'Άδεια κυκλοφορίας ρυμουλκούμενου: υποχρεώσεις και προϋποθέσεις',
            titleEn: 'Trailer registration licence: obligations and requirements',
            textEl:  'Ποιες κατηγορίες ρυμουλκούμενων (Ο1–Ο4) απαιτούν ειδική άδεια, τι ισχύει για βαρέα φορτηγά και πώς εκδίδεται νόμιμα το σημείωμα ρυμούλκησης.',
            textEn:  'Which trailer categories (O1–O4) require a special licence, what applies to heavy trucks and how to legally obtain the towing note.',
        },
        {
            url:     'https://www.atic-ts.com/brief-analysis-of-eu-regulation-2018858-individual-vehicle-approval-iva/',
            catEl:   'Οχήματα Ειδικής Χρήσης',
            catEn:   'Special Use Vehicles',
            titleEl: 'Αδειοδότηση οχημάτων ειδικής χρήσης — ειδικού σκοπού',
            titleEn: 'Licensing of special use — special purpose vehicles',
            textEl:  'Έγκριση ταξινόμησης οχημάτων Ειδικής Χρήσης–Ειδικού Σκοπού που δεν εκτελούν μεταφορικό έργο: δικαιολογητικά, αρμόδιες υπηρεσίες, διαδικασία.',
            textEn:  'Classification approval for Special Use–Special Purpose vehicles not performing transport work: documents, competent authorities, procedure.',
        },
        {
            url:     'https://adrbook.com/en/2017/ADR/9.1.2',
            catEl:   'Γερανοί και Ανυψωτικά',
            catEn:   'Cranes and Lifting',
            titleEl: 'Τοποθέτηση γερανού σε όχημα: νέα άδεια κυκλοφορίας',
            titleEn: 'Crane installation on a vehicle: new circulation permit',
            textEl:  'Η τοποθέτηση γερανού σε όχημα απαιτεί πλήρη μελέτη στατικής επάρκειας, πιστοποιητικό ανύψωσης και έκδοση νέας άδειας κυκλοφορίας.',
            textEn:  'Installing a crane on a vehicle requires a full static adequacy study, lifting certificate and issuance of a new circulation permit.',
        },
        {
            url:     'https://eur-lex.europa.eu/eli/reg/2018/858/oj/eng',
            catEl:   'Εποπτεία Αγοράς ΕΕ',
            catEn:   'EU Market Surveillance',
            titleEl: 'Εποπτεία αγοράς και έγκριση ΕΕ για οχήματα και ρυμουλκούμενα',
            titleEn: 'Market surveillance and EU approval for vehicles and trailers',
            textEl:  'Η ΕΕ ορίζει ενιαίο σύστημα εποπτείας αγοράς για οχήματα και ρυμουλκούμενα, διασφαλίζοντας ότι τα εγκεκριμένα οχήματα πληρούν όλες τις τεχνικές απαιτήσεις.',
            textEn:  'The EU establishes a unified market surveillance system for vehicles and trailers, ensuring approved vehicles meet all technical requirements.',
        },
        {
            url:     'https://www.eurowag.com/blog/towing-trailers-on-european-highways-essential-rules-and-tips-for-safe-and-legal-trailer-towing',
            catEl:   'Σημείωμα Ρυμούλκησης',
            catEn:   'Towing Note',
            titleEl: 'Σημείωμα ρυμούλκησης σε Ι.Χ.: πότε χρειάζεται και πώς εκδίδεται',
            titleEn: 'Towing note for private vehicle: when needed and how to obtain it',
            textEl:  'Κάθε επιβατικό αυτοκίνητο που ρυμουλκεί τροχόσπιτο, μπαγκαζιέρα ή λέμβο χρειάζεται ειδικό σημείωμα προσάρτησης. Δείτε τα δικαιολογητικά και τη διαδικασία.',
            textEn:  'Every private car towing a caravan, cargo trailer or boat needs a special attachment note. See the documents and procedure.',
        },
        {
            url:     'https://www.nsai.ie/images/uploads/certification-automotive/Guidance_doc_O1_O2_O3_O4_rev_01.pdf',
            catEl:   'Άδεια Κυκλοφορίας',
            catEn:   'Circulation Permit',
            titleEl: 'Έκδοση άδειας κυκλοφορίας ρυμουλκούμενου Ι.Χ. — κατηγορίες Ο1 και Ο2',
            titleEn: 'Private trailer circulation permit — O1 and O2 categories',
            textEl:  'Βήμα-βήμα οδηγός για νέα ταξινόμηση ή μεταβίβαση ρυμουλκούμενου κατηγορίας Ο1 ή Ο2. Απαιτούμενα έγγραφα, παράβολα και αρμόδιες υπηρεσίες.',
            textEn:  'Step-by-step guide for new registration or transfer of an O1 or O2 trailer. Required documents, fees and competent authorities.',
        },
        {
            url:     'https://www.atic-ts.com/european-transportation-of-dangerous-goods-adr/',
            catEl:   'Επικίνδυνα Φορτία ADR',
            catEn:   'ADR Dangerous Goods',
            titleEl: 'Άδεια κυκλοφορίας οχήματος ADR: απαιτήσεις και πιστοποίηση',
            titleEn: 'ADR vehicle circulation permit: requirements and certification',
            textEl:  'Οχήματα μεταφοράς επικίνδυνων εμπορευμάτων (EX/II, EX/III, FL, AT, MEMU) απαιτούν ειδική άδεια κυκλοφορίας ADR και τακτικούς ελέγχους συμμόρφωσης.',
            textEn:  'Vehicles transporting dangerous goods (EX/II, EX/III, FL, AT, MEMU) require a special ADR circulation permit and regular compliance checks.',
        },
        {
            url:     'https://osha.europa.eu/en/legislation/directives/directive-2006-42-ec-of-the-european-parliament-and-of-the-council',
            catEl:   'Πιστοποίηση CE',
            catEn:   'CE Certification',
            titleEl: 'Πιστοποίηση CE μηχανών — Οδηγία 2006/42/ΕΚ και ΠΔ 57/2010',
            titleEn: 'CE certification of machinery — Directive 2006/42/EC and PD 57/2010',
            textEl:  'Κάθε ανυψωτικό μηχάνημα που κυκλοφορεί στην ΕΕ πρέπει να φέρει σήμανση CE. Η οδηγία 2006/42/ΕΚ ορίζει τις ουσιώδεις απαιτήσεις υγείας και ασφάλειας.',
            textEn:  'Every lifting machine circulating in the EU must bear CE marking. Directive 2006/42/EC sets out the essential health and safety requirements.',
        },
        {
            url:     'https://eur-lex.europa.eu/EN/legal-content/summary/type-approval-requirements-to-ensure-the-general-safety-of-vehicles-and-the-protection-of-vulnerable-road-users.html',
            catEl:   'Ασφάλεια Οχημάτων ΕΕ',
            catEn:   'EU Vehicle Safety',
            titleEl: 'Κανονισμός ΕΕ 2019/2144: ασφάλεια και προστασία ευάλωτων χρηστών',
            titleEn: 'EU Regulation 2019/2144: safety and protection of vulnerable users',
            textEl:  'Ο κανονισμός 2019/2144 εισάγει νέες τεχνικές απαιτήσεις έγκρισης τύπου για οχήματα, ενισχύοντας την προστασία πεζών, ποδηλατών και επιβατών.',
            textEn:  'Regulation 2019/2144 introduces new type approval technical requirements for vehicles, enhancing protection for pedestrians, cyclists and passengers.',
        },
        {
            url:     'https://drivers-vehicles.services.gov.gr/',
            catEl:   'Ψηφιακές Υπηρεσίες',
            catEn:   'Digital Services',
            titleEl: 'Ψηφιακές υπηρεσίες αδειών οδήγησης και κυκλοφορίας — gov.gr',
            titleEn: 'Digital driving and circulation licence services — gov.gr',
            textEl:  'Η πύλη drivers-vehicles.services.gov.gr συγκεντρώνει όλες τις ψηφιακές υπηρεσίες για άδειες οδήγησης, κυκλοφορίας και τεχνικό έλεγχο στη μία πλατφόρμα.',
            textEn:  'The portal drivers-vehicles.services.gov.gr consolidates all digital services for driving licences, circulation permits and technical inspections in one platform.',
        },
    ],

    // ── GOOGLE REVIEWS ────────────────────────────────────────────────────
    reviews: [
        {
            name: 'Miltos Athanasiou',
            textEl: 'Εξαιρετικός επαγγελματίας, μου εκανε δύο άδειες τρέιλερ πολύ άμεσα στην Σαλαμινα, γρήγορη εξυπηρέτηση, άμεση ανταπόκριση και πολύ λογικές τιμές, κανένα παράπονο, ανέλαβε και διεκπαιρεωσε την διαδικασία από την αρχή μέχρι το τέλος.',
            textEn: 'An excellent professional. He issued two trailer licences for me very quickly in Salamina: fast service, immediate response and very reasonable prices. No complaints at all. He took on the whole process and handled it from start to finish.',
        },
        {
            name: 'Dimitrios Taskoudis',
            textEl: 'Πραγματικά εξαιρετική συνεργασία με τον κ. Μουδιώτη για τη διασκευή του van σε αυτοκινούμενο. Από την πρώτη στιγμή ήταν πολύ εξυπηρετικός, άμεσος και πρόθυμος να εξηγήσει κάθε λεπτομέρεια. Ήξερε ακριβώς τι χρειάζεται, μας καθοδήγησε σωστά σε όλη τη διαδικασία και κυρίως ήταν πάντα διαθέσιμος όταν χρειάστηκε. Η υπόθεση προχώρησε πολύ πιο εύκολα και γρήγορα απ’ όσο περιμέναμε, με συνεχή ενημέρωση και χωρίς περιττό άγχος. Φαίνεται ότι έχει μεγάλη εμπειρία στο αντικείμενο και πραγματικά ενδιαφέρεται να βρει λύση. Πολύ καλή εξυπηρέτηση και λογική χρέωση. Τον προτείνω με κλειστά μάτια!',
            textEn: 'A truly excellent collaboration with Mr. Moudiotis on converting our van into a motorhome. From the very first moment he was very helpful, prompt and willing to explain every detail. He knew exactly what was needed, guided us properly through the whole process and, above all, was always available when needed. The case went much more easily and quickly than we expected, with constant updates and no unnecessary stress. He clearly has great experience in the field and genuinely cares about finding a solution. Very good service and a reasonable fee. I recommend him with my eyes closed!',
        },
        {
            name: 'Βάιος Λιάπης',
            textEl: 'Εξαιρετικός μηχανικός με βαθειά γνώση στο αντικείμενό του. Προτίθεται να ασχοληθεί με τον πελάτη του σε βαθμό που δεν το συναντάς στην αγορά εργασίας. Συνιστώ ανεπιφύλακτα! Ξεχωρίζει για τη φιλική του προσέγγιση, ευγένεια και επαγγελματισμό.',
            textEn: 'An excellent engineer with deep knowledge of his field. He is willing to engage with his clients to a degree you rarely find in the market. Highly recommended! He stands out for his friendly approach, courtesy and professionalism.',
        },
        {
            name: 'Sakis Kyriakou',
            textEl: 'Άψογη συνεργασία από την πρώτη επικοινωνία μέχρι και την ολοκλήρωση της διαδικασίας. Η καταχώρηση του οχήματος στο ΤΑΟ και η έκδοση του Δελτίου Κοινοποίησης έγιναν γρήγορα, οργανωμένα και χωρίς περιττή ταλαιπωρία. Αυτό που πραγματικά ξεχωρίζει είναι η συνέπεια και η άμεση ενημέρωση σε κάθε στάδιο. Υπήρχε συνεχής επικοινωνία και ξεκάθαρη καθοδήγηση για τα δικαιολογητικά και τις απαραίτητες ενέργειες, χωρίς να χρειάζεται να αναζητάς μόνος σου πληροφορίες ή να περιμένεις χωρίς να γνωρίζεις τι γίνεται. Η όλη διαδικασία πραγματοποιήθηκε με επαγγελματισμό, ταχύτητα και υπευθυνότητα. Οι χρεώσεις ήταν λογικές και η εξυπηρέτηση πραγματικά άμεση. Επαγγελματίας που γνωρίζει πολύ καλά τη διαδικασία και φροντίζει να ολοκληρωθεί σωστά και όσο το δυνατόν πιο γρήγορα. Σίγουρα θα τον επέλεγα ξανά και τον προτείνω ανεπιφύλακτα.',
            textEn: 'Flawless collaboration from the first contact through to the completion of the process. Registering the vehicle in the TAO and issuing the Notification Certificate were done quickly, in an organised way and without unnecessary hassle. What really stands out is the consistency and prompt updates at every stage. There was constant communication and clear guidance on the documents and the required steps, so you never had to search for information yourself or wait without knowing what was going on. The whole process was carried out with professionalism, speed and responsibility. The fees were reasonable and the service truly immediate. A professional who knows the process very well and makes sure it is completed correctly and as quickly as possible. I would definitely choose him again and recommend him without reservation.',
        },
        {
            name: 'Giannis Milios',
            textEl: 'Εξαιρετικός επαγγελματίας! Από την πρώτη επικοινωνία μέχρι την ολοκλήρωση της διαδικασίας, η εξυπηρέτηση ήταν άψογη. Άμεση ανταπόκριση, σωστή ενημέρωση, μεγάλη γνώση του αντικειμένου και κυρίως συνέπεια και αξιοπιστία. Όλα έγιναν γρήγορα και χωρίς περιττή ταλαιπωρία, ενώ κάθε απορία μου απαντήθηκε με σαφήνεια. Είναι πραγματικά σημαντικό να συνεργάζεσαι με ανθρώπους που γνωρίζουν πολύ καλά τη δουλειά τους και σου εμπνέουν εμπιστοσύνη. Συστήνω τον Κ. Μουδιώτη ανεπιφύλακτα!',
            textEn: 'An excellent professional! From the first contact to the completion of the process, the service was impeccable. Immediate response, accurate information, deep knowledge of the field and, above all, consistency and reliability. Everything was done quickly and without unnecessary hassle, and every question I had was answered clearly. It really matters to work with people who know their job very well and inspire trust. I recommend Mr. Moudiotis without reservation!',
        },
        {
            name: 'Christos Karopoulos',
            textEl: 'Εξαιρετικές υπηρεσίες του μηχανολόγου μηχανικού Μουδιώτη σε πληρότητα και ποιότητα, άμεσος προγραμματισμός εργασιών, συνεχής διαθεσιμότητα για την επίλυση τυχόν προβλημάτων και όλα αυτά με απολύτως λογική αμοιβή. Συστήνεται ανεπιφύλακτα.',
            textEn: 'Excellent services from mechanical engineer Moudiotis, thorough and high quality, immediate scheduling of work, constant availability to resolve any issues, all at a perfectly reasonable fee. Highly recommended.',
        },
        {
            name: 'Στέλλα Τσέλιου',
            textEl: 'Πολύ καλός επαγγελματίας! Βοήθησε στην άμεση έκδοση άδειας του τρέιλερ του πατέρα μου.',
            textEn: 'Very good professional! He helped with the immediate issuance of my father’s trailer licence.',
        },
        {
            name: 'Vassilios Mazis',
            textEl: 'Το είπε και το έκανε.',
            textEn: 'He said it and he did it.',
        },
        {
            name: 'Ελένη Σταματοπούλου',
            textEl: 'Εξαιρετικό τεχνικό γραφείο! Η κατάρτιση, η υπευθυνότητα και η συνέπεια του μηχανικού κου Μουδιώτη Δημήτρη μας εντυπωσίασε και μας συγκίνησε. Διεκπεραίωσε την υπόθεσή μας άμεσα και με απόλυτη επαγγελματική συνέπεια.',
            textEn: 'Excellent technical office! The expertise, responsibility and consistency of engineer Mr. Dimitrios Moudiotis impressed and moved us. He handled our case immediately and with absolute professional consistency.',
        },
        {
            name: 'Vaios K',
            textEl: 'Άριστη εμπειρία με το τεχνικό γραφείο! Επαγγελματισμός υψηλού επιπέδου, άριστη τεχνική κατάρτιση και άμεση ανταπόκριση σε κάθε ερώτημα. Η συνολική συνεργασία ήταν πολύ ικανοποιητική και τους συστήνω ανεπιφύλακτα.',
            textEn: 'Excellent experience with the technical office! High-level professionalism, excellent technical expertise and immediate response to every question. The overall collaboration was very satisfying and I recommend them without reservation.',
        },
        {
            name: 'Nikolaos Papadopoulos',
            textEl: 'Συνεργάστηκα άψογα με τον Κ. Μουδιώτη, αν θέλετε να γίνει γρήγορα και σωστά η δουλειά σας, σας τον προτείνω ανεπιφύλακτα.',
            textEn: 'I worked flawlessly with Mr. Moudiotis. If you want your work done quickly and correctly, I recommend him without reservation.',
        },
        {
            name: 'Konstantinos Panagiotatos',
            textEl: 'Άψογη εξυπηρέτηση από την αρχή μέχρι το τέλος! Η διαδικασία για την μελέτη και την άδεια του οχήματος ολοκληρώθηκε χωρίς καμία ταλαιπωρία.',
            textEn: 'Impeccable service from start to finish! The process for the vehicle study and licence was completed without any hassle.',
        },
        {
            name: 'Αλέξανδρος Μυλωνάς',
            textEl: 'Εξαιρετική εξυπηρέτηση και απόλυτος επαγγελματισμός! Ο κ. Μουδιώτης ανέλαβε όλη τη διαδικασία για την άδεια του τρέιλερ μου γρήγορα, σωστά και χωρίς καμία ταλαιπωρία.',
            textEn: 'Excellent service and absolute professionalism! Mr. Moudiotis handled the entire process for my trailer licence quickly, correctly and without any hassle.',
        },
        {
            name: 'Stavros Malliaris',
            textEl: 'Χρειαστήκα τον Δημήτρη για μια μελέτη μηχανικού. Μιλήσαμε στο τηλέφωνο, δώσαμε ραντεβού και όλα κύλησαν πολύ εύκολα, χωρίς εκπλήξεις στην τιμή και στην ώρα τους. Είναι ενημερωμένος και ξέρει για τι μιλάει. Συστήνω 👌',
            textEn: 'I needed Dimitris for an engineering study. We spoke on the phone, arranged an appointment and everything went very smoothly, no surprises on price or timing. He’s well informed and knows what he’s talking about. Recommended 👌',
        },
        {
            name: 'Filippos Beck',
            textEl: 'Θα ήθελα να ευχαριστήσω θερμά για τον χρόνο, την προθυμία και την ουσιαστική βοήθεια που μου προσφέρατε σχετικά με την υπόθεσή μας. Παρότι επικοινώνησα μαζί σας με αρκετές απορίες και λεπτομέρειες που έπρεπε να ξεκαθαριστούν, αφιερώσατε χρόνο για να απαντήσετε με σαφήνεια και υπομονή σε κάθε ερώτημα, ενώ στη συνέχεια μου αποστείλατε και το σχετικό ενημερωτικό υλικό και τις εγκυκλίους που αφορούν την εισαγωγή του οχήματος, τη μετοικεσία, καθώς και τα ζητήματα που σχετίζονται με οχήματα αμερικανικών προδιαγραφών. Σπάνια συναντά κανείς τόσο άμεση, κατατοπιστική και ουσιαστική ανταπόκριση σε ένα θέμα με τόσες ιδιαιτερότητες και γραφειοκρατικές λεπτομέρειες. Σας ευχαριστώ ειλικρινά για τον επαγγελματισμό σας και για την πολύτιμη συμβολή σας στην υπόθεσή μας. Η βοήθειά σας ήταν πραγματικά καθοριστική!',
            textEn: 'I would like to warmly thank you for the time, willingness and substantial help you offered with our case. Although I contacted you with several questions and details that needed clarifying, you took the time to answer each one clearly and patiently, and afterwards sent me the relevant informational material and circulars on importing the vehicle, relocation formalities, and issues concerning vehicles with American specifications. It’s rare to find such direct, informative and substantial support on a matter with so many particularities and bureaucratic details. Thank you sincerely for your professionalism and your valuable contribution to our case — your help was truly decisive!',
        },
        {
            name: 'Spyros Damigos',
            textEl: 'Η συνεργασία μου με τον Κο Μουδιώτη εξαιρετική, επαγγελματίας στο είδος του. Συστήνεται ανεπιφύλακτα.',
            textEn: 'My collaboration with Mr. Moudiotis was excellent — a true professional in his field. Highly recommended.',
        },
        {
            name: 'St. Leon',
            textEl: 'Άψογος επαγγελματίας με συνέπεια. 2 άδειες τρέιλερ χωρίς χάσιμο χρόνου. Προτείνεται ανεπιφύλακτα.',
            textEn: 'An impeccable, reliable professional. 2 trailer licences with no time wasted. Highly recommended.',
        },
        {
            name: 'Ioannis Mastrogiorgis',
            textEl: 'Άψογος επαγγελματίας με συνέπεια.',
            textEn: 'An impeccable, reliable professional.',
        },
    ],

    // ── FORM OPTIONS ──────────────────────────────────────────────────────
    formOptions: [
        { el: 'Άδεια Τρέιλερ Ο1 — Ταξινόμηση (έως 750 kg)',     en: 'O1 Trailer Licence — Registration (up to 750 kg)' },
        { el: 'Άδεια Τρέιλερ Ο2 — Ταξινόμηση (έως 3,5 τόνους)', en: 'O2 Trailer Licence — Registration (up to 3.5 t)' },
        { el: 'Ταξινόμηση Οχήματος Ειδικής Χρήσης / Έγκριση Τύπου', en: 'Special Use Vehicle Registration / Type Approval' },
        { el: 'Εθνική / Ευρωπαϊκή Έγκριση Τύπου',                 en: 'National / European Type Approval' },
        { el: 'Μεμονωμένη Έγκριση Οχήματος',                      en: 'Individual Vehicle Approval' },
        { el: 'Καταχώρηση ΤΑΟ / Δελτίο Κοινοποίησης',             en: 'TAO Registration / Notification Certificate' },
        { el: 'Μελέτη Μετασκευής / Ειδικής Κατασκευής',           en: 'Conversion / Special Bodywork Study' },
        { el: 'Βεβαίωση Συμμόρφωσης / Τεχνικό Υπόμνημα',          en: 'Compliance Certificate / Technical Memorandum' },
        { el: 'Τοποθέτηση Γερανού σε Όχημα',                    en: 'Vehicle Crane Installation' },
        { el: 'Ταξινόμηση Τροχόσπιτου',                           en: 'Caravan Registration' },
        { el: 'Μετατροπή Βαν σε Αυτοκινούμενο Τροχόσπιτο',        en: 'Van to Motor Caravan Conversion' },
        // Κρυφά (όχι οχήματα) — για μελλοντική χρήση:
        // { el: 'Μελέτη Γερανού / Υδραυλικής Πλατφόρμας',          en: 'Crane / Hydraulic Platform Study' },
        // { el: 'Τεχνικός Ασφαλείας / ΓΕΕΚ',                        en: 'Safety Engineer / Risk Assessment' },
        // { el: 'Μηχανολογικός Σχεδιασμός / 3D Print',               en: 'Mechanical Design / 3D Print' },
        { el: 'Άλλο',                                              en: 'Other' },
    ],

};
